var _____WB$wombat$assign$function_____ = function(name) {return (self._wb_wombat && self._wb_wombat.local_init && self._wb_wombat.local_init(name)) || self[name]; };
if (!self.__WB_pmw) { self.__WB_pmw = function(obj) { this.__WB_source = obj; return this; } }
{
  let window = _____WB$wombat$assign$function_____("window");
  let self = _____WB$wombat$assign$function_____("self");
  let document = _____WB$wombat$assign$function_____("document");
  let location = _____WB$wombat$assign$function_____("location");
  let top = _____WB$wombat$assign$function_____("top");
  let parent = _____WB$wombat$assign$function_____("parent");
  let frames = _____WB$wombat$assign$function_____("frames");
  let opener = _____WB$wombat$assign$function_____("opener");

window.mwPerformance=(window.performance&&performance.mark)?performance:{mark:function(){}};window.mwNow=(function(){var perf=window.performance,navStart=perf&&perf.timing&&perf.timing.navigationStart;return navStart&&typeof perf.now==='function'?function(){return navStart+perf.now();}:function(){return Date.now();};}());window.isCompatible=function(str){var ua=str||navigator.userAgent;return!!((function(){'use strict';return!this&&!!Function.prototype.bind&&!!window.JSON;}())&&'querySelector'in document&&'localStorage'in window&&'addEventListener'in window&&!(ua.match(/MSIE 10|webOS\/1\.[0-4]|SymbianOS|Series60|NetFront|Opera Mini|S40OviBrowser|MeeGo|Android.+Glass|^Mozilla\/5\.0 .+ Gecko\/$|googleweblight/)||ua.match(/PlayStation/i)));};(function(){var NORLQ,script;if(!isCompatible()){document.documentElement.className=document.documentElement.className.replace(/(^|\s)client-js(\s|$)/,'$1client-nojs$2');NORLQ=window.NORLQ||[];while(NORLQ.length){NORLQ.shift()();}window.NORLQ={push:
function(fn){fn();}};window.RLQ={push:function(){}};return;}function startUp(){mw.config=new mw.Map(true);mw.loader.addSource({"local":"/wiki/load.php"});mw.loader.register([["site","1af7fza",[1]],["site.styles","16n35rq",[],"site"],["noscript","1cole7v",[],"noscript"],["filepage","11mk23k"],["user.groups","1oxilri",[5]],["user","0dpmn5y",[6],"user"],["user.styles","08s97fs",[],"user"],["user.defaults","0xmhbap"],["user.options","0r5ungb",[7],"private"],["user.tokens","00axhui",[],"private"],["mediawiki.language.data","1pox0t6",[177]],["mediawiki.skinning.elements","1c6acgy"],["mediawiki.skinning.content","0uxxj15"],["mediawiki.skinning.interface","1cj1lfg"],["mediawiki.skinning.content.parsoid","0qsnh83"],["mediawiki.skinning.content.externallinks","13rqr1u"],["jquery.accessKeyLabel","0mh10u0",[22,130]],["jquery.async","0y75lxd"],["jquery.byteLength","0o2bam0",[131]],["jquery.byteLimit","1oxilri",[37]],["jquery.checkboxShiftClick","1bh5doz"],["jquery.chosen","07wtgfe"],[
"jquery.client","002wlw2"],["jquery.color","0atys7b",[24]],["jquery.colorUtil","1g64rx4"],["jquery.confirmable","0ft38nn",[178]],["jquery.cookie","0hwzc62"],["jquery.expandableField","1x99eu0"],["jquery.farbtastic","13m7gsr",[24]],["jquery.footHovzer","1pymabm"],["jquery.form","1sws2en"],["jquery.fullscreen","08709mf"],["jquery.getAttrs","1uh4x08"],["jquery.hidpi","0jtwxes"],["jquery.highlightText","1ah32o8",[130]],["jquery.hoverIntent","0sw209l"],["jquery.i18n","0ogpq0w",[176]],["jquery.lengthLimit","0zl2n54",[131]],["jquery.localize","18ri851"],["jquery.makeCollapsible","0enkmgv"],["jquery.mockjax","0nk49oi"],["jquery.mw-jump","1x9mdn4"],["jquery.qunit","18t8tia"],["jquery.spinner","0h7rlhz"],["jquery.jStorage","005j613"],["jquery.suggestions","0cnatt0",[34]],["jquery.tabIndex","0p6mi85"],["jquery.tablesorter","0dltm1b",[130,179]],["jquery.textSelection","0p20r5l",[22]],["jquery.throttle-debounce","1gjdd72"],["jquery.xmldom","1ppdqkx"],["jquery.tipsy","1bomeer"],["jquery.ui.core",
"08eeznj",[53],"jquery.ui"],["jquery.ui.core.styles","09odgtp",[],"jquery.ui"],["jquery.ui.accordion","0zohuq6",[52,72],"jquery.ui"],["jquery.ui.autocomplete","05lmd2v",[61],"jquery.ui"],["jquery.ui.button","123408m",[52,72],"jquery.ui"],["jquery.ui.datepicker","17u1la4",[52],"jquery.ui"],["jquery.ui.dialog","1gedgsy",[56,59,63,65],"jquery.ui"],["jquery.ui.draggable","18qf348",[52,62],"jquery.ui"],["jquery.ui.droppable","1mbithx",[59],"jquery.ui"],["jquery.ui.menu","0lsfl38",[52,63,72],"jquery.ui"],["jquery.ui.mouse","1e9x3cc",[72],"jquery.ui"],["jquery.ui.position","0x0od6l",[],"jquery.ui"],["jquery.ui.progressbar","034ko02",[52,72],"jquery.ui"],["jquery.ui.resizable","0lke5kf",[52,62],"jquery.ui"],["jquery.ui.selectable","1t4pd04",[52,62],"jquery.ui"],["jquery.ui.slider","02ww1oo",[52,62],"jquery.ui"],["jquery.ui.sortable","07z06fo",[52,62],"jquery.ui"],["jquery.ui.spinner","0nhe3rc",[56],"jquery.ui"],["jquery.ui.tabs","0ffqe0b",[52,72],"jquery.ui"],["jquery.ui.tooltip","0c3vjir",[52
,63,72],"jquery.ui"],["jquery.ui.widget","14gzvfm",[],"jquery.ui"],["jquery.effects.core","1rao6in",[],"jquery.ui"],["jquery.effects.blind","1rrgndy",[73],"jquery.ui"],["jquery.effects.bounce","0jm77ze",[73],"jquery.ui"],["jquery.effects.clip","1le7seb",[73],"jquery.ui"],["jquery.effects.drop","0tqzmzn",[73],"jquery.ui"],["jquery.effects.explode","1ps2skc",[73],"jquery.ui"],["jquery.effects.fade","16f54my",[73],"jquery.ui"],["jquery.effects.fold","121uf8m",[73],"jquery.ui"],["jquery.effects.highlight","1pa7k6w",[73],"jquery.ui"],["jquery.effects.pulsate","056q0cg",[73],"jquery.ui"],["jquery.effects.scale","0zomizc",[73],"jquery.ui"],["jquery.effects.shake","1rfalq3",[73],"jquery.ui"],["jquery.effects.slide","1sna7ro",[73],"jquery.ui"],["jquery.effects.transfer","0uzconm",[73],"jquery.ui"],["json","1oxilri"],["moment","17ljrf4",[174]],["mediawiki.apihelp","1d8ct2j"],["mediawiki.template","0kbafhn"],["mediawiki.template.mustache","03xm7g7",[90]],["mediawiki.template.regexp","04j2pyl",[90
]],["mediawiki.apipretty","0pykb1l"],["mediawiki.api","1783xsq",[148,9]],["mediawiki.api.category","1bg2lda",[136,94]],["mediawiki.api.edit","1ht5csx",[146]],["mediawiki.api.login","1o6c7qq",[94]],["mediawiki.api.options","0wd4ymc",[94]],["mediawiki.api.parse","18rvcwm",[94]],["mediawiki.api.upload","0n2jk5g",[96]],["mediawiki.api.user","1wpekes",[94]],["mediawiki.api.watch","14w2taw",[94]],["mediawiki.api.messages","1o014p1",[94]],["mediawiki.api.rollback","0nrhyy2",[94]],["mediawiki.content.json","1cjxvm5"],["mediawiki.confirmCloseWindow","1qhqkvv"],["mediawiki.debug","0pt6ggt",[29,273]],["mediawiki.diff.styles","111uhhg"],["mediawiki.feedback","115y8nd",[136,124,277]],["mediawiki.feedlink","06kdhjr"],["mediawiki.filewarning","1ttte5u",[273]],["mediawiki.ForeignApi","0ld9lr0",[113]],["mediawiki.ForeignApi.core","0o7n6cg",[94,269]],["mediawiki.helplink","1ijgahz"],["mediawiki.hidpi","0h4fol6",[33],null,null,"return'srcset'in new Image();"],["mediawiki.hlist","1yzf79h"],[
"mediawiki.htmlform","0ojf1xb",[37,130]],["mediawiki.htmlform.checker","1304cz1",[49]],["mediawiki.htmlform.ooui","07r2syn",[273]],["mediawiki.htmlform.styles","1n5xmp3"],["mediawiki.htmlform.ooui.styles","068gxkw"],["mediawiki.icon","1qgh5oh"],["mediawiki.inspect","0e2g0yf",[130,131]],["mediawiki.messagePoster","0zkjn39",[112]],["mediawiki.messagePoster.wikitext","0nk15by",[96,124]],["mediawiki.notification","0wb0fjy",[148,156]],["mediawiki.notify","1twjime"],["mediawiki.notification.convertmessagebox","0gvbb2v",[126]],["mediawiki.notification.convertmessagebox.styles","1tcycx0"],["mediawiki.RegExp","0fkv2h2"],["mediawiki.String","14cvrfw"],["mediawiki.pager.tablePager","1xlv40n"],["mediawiki.searchSuggest","199l0sq",[32,45,94]],["mediawiki.sectionAnchor","0u866ta"],["mediawiki.storage","0pmxt25"],["mediawiki.Title","0h1u0dn",[131,148]],["mediawiki.Upload","0om3rny",[100]],["mediawiki.ForeignUpload","01pn0g0",[112,137]],["mediawiki.ForeignStructuredUpload.config","0msydx9"],[
"mediawiki.ForeignStructuredUpload","0h2x0q9",[139,138]],["mediawiki.Upload.Dialog","0z7c3vj",[142]],["mediawiki.Upload.BookletLayout","1bi6nna",[136,137,178,266,88,275,277]],["mediawiki.ForeignStructuredUpload.BookletLayout","0yid79g",[140,142,103,182,256,251]],["mediawiki.toc","1b64y0g",[152]],["mediawiki.Uri","1xvhbq6",[148,92]],["mediawiki.user","03hewn0",[101,135,8]],["mediawiki.userSuggest","0a1pdyd",[45,94]],["mediawiki.util","1hwa75w",[16,127]],["mediawiki.viewport","1c8xd2l"],["mediawiki.checkboxtoggle","0z8bnn6"],["mediawiki.checkboxtoggle.styles","054tcej"],["mediawiki.cookie","1i9nm4s",[26]],["mediawiki.toolbar","03gt8t2",[48]],["mediawiki.experiments","0cipp3t"],["mediawiki.editfont.styles","122qs77"],["mediawiki.visibleTimeout","1vfq6an"],["mediawiki.action.delete","1nujl19",[37,273]],["mediawiki.action.delete.file","1lusu86",[37]],["mediawiki.action.edit","06g3uab",[48,160,94,155,254]],["mediawiki.action.edit.styles","1drn8d3"],["mediawiki.action.edit.collapsibleFooter",
"1hg9bbp",[39,122,135]],["mediawiki.action.edit.preview","0di5sdi",[43,48,94,108,178,273]],["mediawiki.action.history","0x6uuny"],["mediawiki.action.history.styles","196ve4i"],["mediawiki.action.view.dblClickEdit","1jk13bz",[148,8]],["mediawiki.action.view.metadata","0j61a6e",[173]],["mediawiki.action.view.categoryPage.styles","14cz72p"],["mediawiki.action.view.postEdit","0zr3joc",[178,126]],["mediawiki.action.view.redirect","1i5v033",[22]],["mediawiki.action.view.redirectPage","0ee68x4"],["mediawiki.action.view.rightClickEdit","0midfch"],["mediawiki.action.edit.editWarning","1v2j59g",[48,106,178]],["mediawiki.action.view.filepage","0qo80oc"],["mediawiki.language","1g1rk71",[175,10]],["mediawiki.cldr","0wat6t3",[176]],["mediawiki.libs.pluralruleparser","110ejpp"],["mediawiki.language.init","10gnjw9"],["mediawiki.jqueryMsg","1ktqnws",[174,148,8]],["mediawiki.language.months","1xo9ciw",[174]],["mediawiki.language.names","0cfo43y",[177]],["mediawiki.language.specialCharacters","0meovla",[
174]],["mediawiki.libs.jpegmeta","1xw1pxk"],["mediawiki.page.gallery","1sj9ifb",[49,184]],["mediawiki.page.gallery.styles","0bs5gks"],["mediawiki.page.gallery.slideshow","08f9s07",[136,94,275,290]],["mediawiki.page.ready","1809xle",[16,20,41]],["mediawiki.page.startup","1gmiv91"],["mediawiki.page.patrol.ajax","1xshizn",[43,136,94]],["mediawiki.page.watch.ajax","16vom3l",[136,102,178]],["mediawiki.page.rollback","1efzp2d",[43,104]],["mediawiki.page.image.pagination","0bnwyi8",[43,148]],["mediawiki.rcfilters.filters.base.styles","1c7efke"],["mediawiki.rcfilters.highlightCircles.seenunseen.styles","16g9qee"],["mediawiki.rcfilters.filters.dm","0fla17o",[131,145,98,178,146,269]],["mediawiki.rcfilters.filters.ui","05r2ftv",[39,194,249,284,286,288,290]],["mediawiki.special","0lzd4jh"],["mediawiki.special.apisandbox.styles","05bmimx"],["mediawiki.special.apisandbox","152vvcb",[39,94,178,255,272]],["mediawiki.special.block","1rilbjl",[117,148,257]],["mediawiki.special.changecredentials.js",
"1i8wugy",[94,119]],["mediawiki.special.changeslist","1fpqxgt"],["mediawiki.special.changeslist.enhanced","1gb4sv5"],["mediawiki.special.changeslist.legend","1l1k9ml"],["mediawiki.special.changeslist.legend.js","1meejm4",[39,152]],["mediawiki.special.changeslist.visitedstatus","11t584h"],["mediawiki.special.comparepages.styles","0kcxogg"],["mediawiki.special.contributions","0nuza3n",[178,251]],["mediawiki.special.edittags","05xm9nm",[21,37]],["mediawiki.special.edittags.styles","07nk387"],["mediawiki.special.import","0yinmfm"],["mediawiki.special.movePage","0jpn5tz",[249,254]],["mediawiki.special.movePage.styles","1c05ixf"],["mediawiki.special.pageLanguage","1g6qsh3",[273]],["mediawiki.special.pagesWithProp","0yitr48"],["mediawiki.special.preferences","0c13nvc",[106,174,128]],["mediawiki.special.preferences.styles","1gpyrah"],["mediawiki.special.recentchanges","0wu3vhk"],["mediawiki.special.revisionDelete","1uw3h74",[37]],["mediawiki.special.search","1tkys04",[264]],[
"mediawiki.special.search.commonsInterwikiWidget","1mrhonp",[145,94,178]],["mediawiki.special.search.interwikiwidget.styles","1xr4rsu"],["mediawiki.special.search.styles","0hjk9zv"],["mediawiki.special.undelete","0rqmgcq",[249,254]],["mediawiki.special.unwatchedPages","0m7nx08",[136,102]],["mediawiki.special.upload","1fq1anr",[43,136,99,106,178,182,226,90]],["mediawiki.special.upload.styles","1otexgv"],["mediawiki.special.userlogin.common.styles","1fkr0gk"],["mediawiki.special.userlogin.login.styles","1vyslho"],["mediawiki.special.userlogin.signup.js","12588wh",[94,118,178]],["mediawiki.special.userlogin.signup.styles","0gip3f6"],["mediawiki.special.userrights","0wlx7nd",[37,128]],["mediawiki.special.watchlist","0mciq2l",[136,102,178,273]],["mediawiki.special.watchlist.styles","16r507w"],["mediawiki.special.version","0j8onfm"],["mediawiki.legacy.config","0s3ugue"],["mediawiki.legacy.commonPrint","1ljha7n"],["mediawiki.legacy.protect","11qf5f2",[37]],["mediawiki.legacy.shared","1t44347"
],["mediawiki.legacy.oldshared","1tkdwmp"],["mediawiki.legacy.wikibits","0joopli"],["mediawiki.ui","0clb0hn"],["mediawiki.ui.checkbox","18ikgrk"],["mediawiki.ui.radio","1b10c32"],["mediawiki.ui.anchor","1j2sjdd"],["mediawiki.ui.button","0cupdga"],["mediawiki.ui.input","10xjgmo"],["mediawiki.ui.icon","0l64wxb"],["mediawiki.ui.text","0vzctuq"],["mediawiki.widgets","0ge14dy",[136,94,250,275]],["mediawiki.widgets.styles","0ly1c9x"],["mediawiki.widgets.DateInputWidget","10lqlhy",[252,88,275]],["mediawiki.widgets.DateInputWidget.styles","0jructd"],["mediawiki.widgets.visibleByteLimit","1oxilri",[254]],["mediawiki.widgets.visibleLengthLimit","06mzqvn",[37,273]],["mediawiki.widgets.datetime","1jwetl6",[273,291,292]],["mediawiki.widgets.CategoryMultiselectWidget","1l4kbf2",[112,136,275]],["mediawiki.widgets.SelectWithInputWidget","0zhtpe8",[258,275]],["mediawiki.widgets.SelectWithInputWidget.styles","1xmeiu7"],["mediawiki.widgets.SizeFilterWidget","1pe6g73",[260,275]],[
"mediawiki.widgets.SizeFilterWidget.styles","0hox5h6"],["mediawiki.widgets.MediaSearch","08jz932",[112,136,275]],["mediawiki.widgets.UserInputWidget","0cpzb56",[94,275]],["mediawiki.widgets.UsersMultiselectWidget","1nqq87c",[94,275]],["mediawiki.widgets.SearchInputWidget","16yymu7",[133,249]],["mediawiki.widgets.SearchInputWidget.styles","1gjew4b"],["mediawiki.widgets.StashedFileWidget","0ni1i65",[94,273]],["es5-shim","1oxilri"],["dom-level2-shim","1oxilri"],["oojs","1tpogqi"],["mediawiki.router","15ap71b",[271]],["oojs-router","1k6mttz",[269]],["oojs-ui","1oxilri",[276,275,277]],["oojs-ui-core","03c9mu8",[174,269,274,281,282,287,278,279]],["oojs-ui-core.styles","085b8i1"],["oojs-ui-widgets","0m2uf4f",[273,283,291,292]],["oojs-ui-toolbars","1a76wci",[273,292]],["oojs-ui-windows","1dilbfv",[273,292]],["oojs-ui.styles.indicators","1dfuhde"],["oojs-ui.styles.textures","1hv9nxe"],["oojs-ui.styles.icons-accessibility","10wcy9v"],["oojs-ui.styles.icons-alerts","0f4fz6v"],[
"oojs-ui.styles.icons-content","0ubwhnt"],["oojs-ui.styles.icons-editing-advanced","18bqzwg"],["oojs-ui.styles.icons-editing-core","0xwfco7"],["oojs-ui.styles.icons-editing-list","0pg6b1v"],["oojs-ui.styles.icons-editing-styling","1skgcho"],["oojs-ui.styles.icons-interactions","1gnsxbm"],["oojs-ui.styles.icons-layout","0jok7rx"],["oojs-ui.styles.icons-location","06u95hh"],["oojs-ui.styles.icons-media","1c4ppw4"],["oojs-ui.styles.icons-moderation","096dz7m"],["oojs-ui.styles.icons-movement","0w1h0ij"],["oojs-ui.styles.icons-user","0d39k3r"],["oojs-ui.styles.icons-wikimedia","0qbnmm1"],["skins.monobook.styles","0mhe05u"],["skins.vector.styles","1bf5w5p"],["skins.vector.styles.responsive","0kh34yx"],["skins.vector.js","1e6nlk0",[46,49]],["ext.cite.styles","0si7ag5"],["ext.cite.a11y","0o0lw7e"],["ext.cite.style","1ohbh76"],["ext.pygments","1922qgu"]]);;mw.config.set({"wgLoadScript":"/wiki/load.php","debug":!1,"skin":"vector","stylepath":"/wiki/skins","wgUrlProtocols":
"bitcoin\\:|ftp\\:\\/\\/|ftps\\:\\/\\/|geo\\:|git\\:\\/\\/|gopher\\:\\/\\/|http\\:\\/\\/|https\\:\\/\\/|irc\\:\\/\\/|ircs\\:\\/\\/|magnet\\:|mailto\\:|mms\\:\\/\\/|news\\:|nntp\\:\\/\\/|redis\\:\\/\\/|sftp\\:\\/\\/|sip\\:|sips\\:|sms\\:|ssh\\:\\/\\/|svn\\:\\/\\/|tel\\:|telnet\\:\\/\\/|urn\\:|worldwind\\:\\/\\/|xmpp\\:|\\/\\/","wgArticlePath":"/wiki/$1","wgScriptPath":"/wiki","wgScript":"/wiki/index.php","wgSearchType":null,"wgVariantArticlePath":!1,"wgActionPaths":{},"wgServer":"http://web.archive.org/web/20200304205102/https://cs61.seas.harvard.edu","wgServerName":"cs61.seas.harvard.edu","wgUserLanguage":"en","wgContentLanguage":"en","wgTranslateNumerals":!0,"wgVersion":"1.31.0","wgEnableAPI":!0,"wgEnableWriteAPI":!0,"wgMainPageTitle":"2018/Home","wgFormattedNamespaces":{"-2":"Media","-1":"Special","0":"","1":"Talk","2":"User","3":"User talk","4":"CS61","5":"CS61 talk","6":"File","7":"File talk","8":"MediaWiki","9":"MediaWiki talk","10":"Template","11":"Template talk","12":"Help","13":"Help talk","14":"Category","15"
:"Category talk"},"wgNamespaceIds":{"media":-2,"special":-1,"":0,"talk":1,"user":2,"user_talk":3,"cs61":4,"cs61_talk":5,"file":6,"file_talk":7,"mediawiki":8,"mediawiki_talk":9,"template":10,"template_talk":11,"help":12,"help_talk":13,"category":14,"category_talk":15,"image":6,"image_talk":7,"project":4,"project_talk":5},"wgContentNamespaces":[0],"wgSiteName":"CS61","wgDBname":"wikidb","wgExtraSignatureNamespaces":[],"wgAvailableSkins":{"monobook":"MonoBook","vector":"Vector","fallback":"Fallback","apioutput":"ApiOutput"},"wgExtensionAssetsPath":"/wiki/extensions","wgCookiePrefix":"wikidb","wgCookieDomain":"","wgCookiePath":"/","wgCookieExpiration":2592000,"wgResourceLoaderMaxQueryLength":2000,"wgCaseSensitiveNamespaces":[],"wgLegalTitleChars":" %!\"$&'()*,\\-./0-9:;=?@A-Z\\\\\\^_`a-z~+\\u0080-\\uFFFF","wgIllegalFileChars":":/\\\\","wgResourceLoaderStorageVersion":1,"wgResourceLoaderStorageEnabled":!0,"wgForeignUploadTargets":["local"],"wgEnableUploads":!0,"wgCommentByteLimit":255,
"wgCommentCodePointLimit":null,"wgCiteVisualEditorOtherGroup":!1,"wgCiteResponsiveReferences":!0});var RLQ=window.RLQ||[];while(RLQ.length){RLQ.shift()();}window.RLQ={push:function(fn){fn();}};window.NORLQ={push:function(){}};}window.mediaWikiLoadStart=mwNow();mwPerformance.mark('mwLoadStart');script=document.createElement('script');script.src="/wiki/load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=1lba87a";script.onload=function(){script.onload=null;script=null;startUp();};document.head.appendChild(script);}());


}
/*
     FILE ARCHIVED ON 20:51:02 Mar 04, 2020 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 09:42:40 Aug 08, 2021.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/
/*
playback timings (ms):
  captures_list: 161.775
  load_resource: 78.269
  CDXLines.iter: 20.952 (3)
  RedisCDXSource: 0.622
  esindex: 0.011
  exclusion.robots.policy: 0.197
  LoadShardBlock: 135.156 (3)
  exclusion.robots: 0.21
  PetaboxLoader3.resolve: 80.063 (2)
  PetaboxLoader3.datanode: 74.551 (4)
*/